apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inner-loop-demo
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
    - unicorn
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=inner-loop-demo'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
